### ISSUE TITLE
Products stream calls undocumented endpoint

### ISSUE THREAD

**Issue by rjh336** [singer-io/tap-yotpo#51]
The products stream calls an endpoint on the UGC API that might have been deprecated
https://github.com/singer-io/tap-yotpo/blob/master/tap_yotpo/streams.py#L264

This stream should be calling the Core API - Retrieve Products endpoint, documented here:
https://core-api.yotpo.com/reference/retrieve-products

Seeing errors like this 
```
2022-10-30 08:00:58,423Z   main - INFO Starting target: target-env/bin/target-stitch --config /tmp/target_config.json
2022-10-30 08:00:58,858Z target - INFO Using batch_size_prefernces of {'full_table_streams': [], 'batch_size_preference': None, 'user_batch_size_preference': None}
2022-10-30 08:01:00,627Z    tap - INFO HTTP request to "products" endpoint took 1.753s, returned status code 200
2022-10-30 08:01:01,911Z    tap - INFO HTTP request to "products" endpoint took 1.250s, returned status code 200
2022-10-30 08:01:03,601Z    tap - INFO HTTP request to "products" endpoint took 1.652s, returned status code 200
2022-10-30 08:01:03,602Z    tap - CRITICAL Unterminated string starting at: line 1 column 28350 (char 28349)
2022-10-30 08:01:03,603Z    tap - Traceback (most recent call last):
2022-10-30 08:01:03,603Z    tap -   File "tap-env/bin/tap-yotpo", line 33, in <module>
2022-10-30 08:01:03,603Z    tap -     sys.exit(load_entry_point('tap-yotpo==1.3.6', 'console_scripts', 'tap-yotpo')())
2022-10-30 08:01:03,603Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 229, in wrapped
2022-10-30 08:01:03,603Z    tap -     return fnc(*args, **kwargs)
2022-10-30 08:01:03,603Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_yotpo/__init__.py", line 89, in main
2022-10-30 08:01:03,604Z    tap -     sync(ctx)
2022-10-30 08:01:03,604Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_yotpo/__init__.py", line 62, in sync
2022-10-30 08:01:03,604Z    tap -     streams_.products.fetch_into_cache(ctx)
2022-10-30 08:01:03,604Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_yotpo/streams.py", line 132, in fetch_into_cache
2022-10-30 08:01:03,604Z    tap -     self._sync(ctx)
2022-10-30 08:01:03,604Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_yotpo/streams.py", line 86, in _sync
2022-10-30 08:01:03,604Z    tap -     resp = ctx.client.GET(self.version, opts, self.tap_stream_id)
2022-10-30 08:01:03,604Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff/_sync.py", line 94, in retry
2022-10-30 08:01:03,604Z    tap -     ret = target(*args, **kwargs)
2022-10-30 08:01:03,604Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_yotpo/http.py", line 177, in GET
2022-10-30 08:01:03,604Z    tap -     return self.request_with_handling(req, *args, **kwargs)
2022-10-30 08:01:03,604Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_yotpo/http.py", line 156, in request_with_handling
2022-10-30 08:01:03,604Z    tap -     return response.json()
2022-10-30 08:01:03,604Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/requests/models.py", line 897, in json
2022-10-30 08:01:03,604Z    tap -     return complexjson.loads(self.text, **kwargs)
2022-10-30 08:01:03,604Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/simplejson/__init__.py", line 516, in loads
2022-10-30 08:01:03,604Z    tap -     return _default_decoder.decode(s)
2022-10-30 08:01:03,604Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/simplejson/decoder.py", line 370, in decode
2022-10-30 08:01:03,604Z    tap -     obj, end = self.raw_decode(s)
2022-10-30 08:01:03,604Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/simplejson/decoder.py", line 400, in raw_decode
2022-10-30 08:01:03,604Z    tap -     return self.scan_once(s, idx=_w(s, idx).end())
2022-10-30 08:01:03,604Z    tap - simplejson.scanner.JSONDecodeError: Unterminated string starting at: line 1 column 28350 (char 28349)
2022-10-30 08:01:03,645Z target - INFO Requests complete, stopping loop
2022-10-30 08:01:03,683Z   main - INFO Target exited normally with status 0
2022-10-30 08:01:05,529Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [5] at offset None
2022-10-30 08:01:05,534Z   main - INFO No tunnel subprocess to tear down
2022-10-30 08:01:05,534Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "Unterminated string starting at: line 1 column 28350 (char 28349)". Target succeeded.
```

cc @Vi6hal @sgandhi1311

**Comment by Vi6hal** [comment]
Hi @rjh336 , thanks for highlighting this.
we are performing an upgrade on this tap, where these api deprecations are taken care of, it will be merged with the master branch once the approvals are in place.

F.Y.I [PR for the changes](https://github.com/singer-io/tap-yotpo/pull/46)
