### ISSUE TITLE
Error:  'NoneType' object is not subscriptable // other data asks?

### ISSUE THREAD

**Issue by bbesash** [singer-io/tap-yotpo#8]
Hello! We just started using this integration this year and are having some errors when replicating from the `product_reviews` table - anyone run into this before? We get this error every extraction run.

Additionally, it was stated on the Stitch documentation that custom attributes on reviews would be included on this table but I don't see any? Also, is there any way that whether the review was approved, published, rejected, or submitted be included in these tables? 

See below for error message on the table:

```2021-01-19 09:48:59,757Z    tap - INFO Sending batch. Max Record 2019-12-31T03:37:35+00:00 is >= bookmark 2017-01-01T00:00:00+00:00
2021-01-19 09:48:59,776Z    tap - INFO HTTP request to "product_reviews" endpoint took 0.023s, returned status code 200
2021-01-19 09:48:59,808Z    tap - INFO HTTP request to "product_reviews" endpoint took 0.031s, returned status code 404
2021-01-19 09:48:59,808Z    tap - CRITICAL 'NoneType' object is not subscriptable
2021-01-19 09:48:59,808Z    tap - Traceback (most recent call last):
2021-01-19 09:48:59,809Z    tap -   File "tap-env/bin/tap-yotpo", line 33, in <module>
2021-01-19 09:48:59,809Z    tap -     sys.exit(load_entry_point('tap-yotpo==1.1.1', 'console_scripts', 'tap-yotpo')())
2021-01-19 09:48:59,809Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_yotpo/__init__.py", line 91, in main
2021-01-19 09:48:59,809Z    tap -     main_impl()
2021-01-19 09:48:59,809Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_yotpo/__init__.py", line 86, in main_impl
2021-01-19 09:48:59,809Z    tap -     sync(ctx)
2021-01-19 09:48:59,809Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_yotpo/__init__.py", line 71, in sync
2021-01-19 09:48:59,809Z    tap -     stream.sync(ctx)
2021-01-19 09:48:59,809Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_yotpo/streams.py", line 205, in sync
2021-01-19 09:48:59,809Z    tap -     self._sync(ctx, path, product_id=product_id)
2021-01-19 09:48:59,809Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_yotpo/streams.py", line 87, in _sync
2021-01-19 09:48:59,809Z    tap -     raw_records = self.format_response(resp)
2021-01-19 09:48:59,809Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_yotpo/streams.py", line 47, in format_response
2021-01-19 09:48:59,809Z    tap -     response = response['response']
2021-01-19 09:48:59,809Z    tap - TypeError: 'NoneType' object is not subscriptable
2021-01-19 09:48:59,847Z target - INFO Serializing batch with 4561 messages for table product_reviews
2021-01-19 09:48:59,918Z target - INFO Sending batch of 3807537 bytes to https://api.stitchdata.com/v2/import/batch
2021-01-19 09:48:59,927Z target - INFO [smart-services] event successfully sent to kafka: com.stitchdata.streamRecordCount [5] at offset None
2021-01-19 09:48:59,927Z target - INFO replicated 4561 records from "product_reviews" endpoint
2021-01-19 09:49:00,858Z target - INFO Requests complete, stopping loop
2021-01-19 09:49:00,915Z   main - INFO Target exited normally with status 0
2021-01-19 09:49:01,730Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [22] at offset None
2021-01-19 09:49:01,730Z   main - INFO No tunnel subprocess to tear down
2021-01-19 09:49:01,731Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "'NoneType' object is not subscriptable". Target succeeded.

**Comment by dave-connors-3** [comment]
Hey @bbesash - We set up a Yotpo integration a few weeks ago, and we're seeing exactly the same issue. Have you had any success in addressing this?

**Comment by bbesash** [comment]
hey @dave-connors-3 - no have not been able to clear this up, just turned off that replication for the time being.

**Comment by sgandhi1311** [comment]
@bbesash did u tried running the tap locally for the stream-`product_review` ?
I think this is indicating a problem in the response you are receiving.
